version: '2'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src/counter
    working_dir: /go/src/counter
    command: /bin/bash -c "go install counter && /go/bin/counter"
